# Module manifest for module 'Passphraser'
# Generated by: Lage Berger Jensen
# Generated on: 23.10.2019

@{
    RootModule        = 'Passphraser.psm1'
    ModuleVersion     = '2.1.0'
    GUID              = 'b40097d7-bc39-4f92-a85d-cc5e39be939a'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) 2023 Lage Berger Jensen. All rights reserved.'
    Description       = 'Powershell passphrase generator'
    FunctionsToExport = @('New-Passphrase')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    RequiredAssemblies = @('.\classes\Zxcvbn.dll')
    ScriptsToProcess  = @('.\classes\PassphraseObject.Class.ps1')
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags = @(
                'passphraser'
                'passphrase',
                'password',
                'generator',
                'entropy,',
                'crack'
            )
            LicenseUri = 'https://github.com/lagebj/Passphraser/blob/master/LICENSE'
            ProjectUri = 'https://github.com/lagebj/Passphraser'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
