# Module manifest for module 'Passphraser'
# Generated by: Lage Berger Jensen
# Generated on: 23.10.2019

@{
    RootModule        = 'Passphraser.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = 'b40097d7-bc39-4f92-a85d-cc5e39be939a'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) Lage Berger Jensen. All rights reserved.'
    Description       = ''
    FunctionsToExport = @('*')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
